name: colbert-v0.2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip=21.0
  - cudatoolkit=11.1
  - pytorch=1.9.0
  - torchvision
  - faiss-gpu=1.7.0
  - pip:
    - mlflow
    - tensorboard
    - tqdm
    - transformers==4.10.0
    - ujson
